-- ============================================
-- 百万级测试数据 - 表结构创建
-- ============================================

USE task_scheduler_dev;

-- 1. MW_ORDER_WORK (工单表)
DROP TABLE IF EXISTS `MW_ORDER_WORK`;
CREATE TABLE `MW_ORDER_WORK` (
  `ID` VARCHAR(100) NOT NULL COMMENT '主键ID',
  `SHEET_ID` VARCHAR(100) DEFAULT NULL COMMENT '工单流水号',
  `TITLE` VARCHAR(200) DEFAULT NULL COMMENT '工单标题',
  `STATUS` VARCHAR(50) DEFAULT NULL COMMENT '工单状态',
  `PRIORITY` VARCHAR(20) DEFAULT NULL COMMENT '优先级',
  `CREATE_TIME` DATETIME DEFAULT NULL COMMENT '创建时间',
  `UPDATE_TIME` DATETIME DEFAULT NULL COMMENT '更新时间',
  `CREATOR` VARCHAR(100) DEFAULT NULL COMMENT '创建人',
  PRIMARY KEY (`ID`),
  KEY `IDX_SHEET_ID` (`SHEET_ID`),
  KEY `IDX_STATUS` (`STATUS`),
  KEY `IDX_CREATE_TIME` (`CREATE_TIME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='工单表';

-- 2. MW_ORDER_WORK_RELATED (工单关联关系表)
DROP TABLE IF EXISTS `MW_ORDER_WORK_RELATED`;
CREATE TABLE `MW_ORDER_WORK_RELATED` (
  `ID` VARCHAR(100) NOT NULL COMMENT '主键ID',
  `SHEET_ID` VARCHAR(100) DEFAULT NULL COMMENT '工单流水号',
  `RELATED_SHEET_ID` VARCHAR(100) DEFAULT NULL COMMENT '关联工单流水号',
  `RELATION_TYPE` VARCHAR(50) DEFAULT NULL COMMENT '关联类型',
  `REMARK` VARCHAR(500) DEFAULT NULL COMMENT '备注',
  `CREATE_TIME` DATETIME DEFAULT NULL COMMENT '创建时间',
  `UPDATE_TIME` DATETIME DEFAULT NULL COMMENT '更新时间',
  `CREATOR` VARCHAR(100) DEFAULT NULL COMMENT '创建人',
  `UPDATER` VARCHAR(100) DEFAULT NULL COMMENT '更新人',
  PRIMARY KEY (`ID`),
  KEY `IDX_SHEET_ID` (`SHEET_ID`),
  KEY `IDX_RELATED_SHEET_ID` (`RELATED_SHEET_ID`),
  KEY `IDX_CREATE_TIME` (`CREATE_TIME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='工单关联关系表';

-- 3. MW_ORDER_CIRCULATE (工单流转表)
DROP TABLE IF EXISTS `MW_ORDER_CIRCULATE`;
CREATE TABLE `MW_ORDER_CIRCULATE` (
  `ID` VARCHAR(100) NOT NULL COMMENT '主键ID',
  `SHEET_ID` VARCHAR(100) DEFAULT NULL COMMENT '工单流水号',
  `CIRCULATE_NO` VARCHAR(100) DEFAULT NULL COMMENT '流转编号',
  `STATUS` VARCHAR(50) DEFAULT NULL COMMENT '流转状态',
  `CREATE_TIME` DATETIME DEFAULT NULL COMMENT '创建时间',
  `UPDATE_TIME` DATETIME DEFAULT NULL COMMENT '更新时间',
  `CREATOR` VARCHAR(100) DEFAULT NULL COMMENT '创建人',
  PRIMARY KEY (`ID`),
  KEY `IDX_SHEET_ID` (`SHEET_ID`),
  KEY `IDX_CIRCULATE_NO` (`CIRCULATE_NO`),
  KEY `IDX_STATUS` (`STATUS`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='工单流转表';

-- 4. MW_ORDER_CIRCULATE_INFO (工单流转节点信息表)
DROP TABLE IF EXISTS `MW_ORDER_CIRCULATE_INFO`;
CREATE TABLE `MW_ORDER_CIRCULATE_INFO` (
  `ID` VARCHAR(100) NOT NULL COMMENT '主键ID',
  `CIRCULATE_ID` VARCHAR(100) DEFAULT NULL COMMENT '流转ID',
  `NODE_NAME` VARCHAR(100) DEFAULT NULL COMMENT '节点名称',
  `NODE_STATUS` VARCHAR(50) DEFAULT NULL COMMENT '节点状态',
  `HANDLE_TIME` DATETIME DEFAULT NULL COMMENT '处理时间',
  `CREATOR` VARCHAR(100) DEFAULT NULL COMMENT '创建人',
  PRIMARY KEY (`ID`),
  KEY `IDX_CIRCULATE_ID` (`CIRCULATE_ID`),
  KEY `IDX_NODE_STATUS` (`NODE_STATUS`),
  KEY `IDX_HANDLE_TIME` (`HANDLE_TIME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='工单流转节点信息表';

-- 5. MW_ORDER_PUBLIC_INCIDENT (公共事件表)
DROP TABLE IF EXISTS `MW_ORDER_PUBLIC_INCIDENT`;
CREATE TABLE `MW_ORDER_PUBLIC_INCIDENT` (
  `ID` VARCHAR(100) NOT NULL COMMENT '主键ID',
  `INCIDENT_NO` VARCHAR(100) DEFAULT NULL COMMENT '事件编号',
  `SHEET_ID` VARCHAR(100) DEFAULT NULL COMMENT '工单流水号',
  `INCIDENT_TYPE` VARCHAR(100) DEFAULT NULL COMMENT '事件类型',
  `SEVERITY` VARCHAR(20) DEFAULT NULL COMMENT '严重程度',
  `OCCUR_TIME` DATETIME DEFAULT NULL COMMENT '发生时间',
  `CREATE_TIME` DATETIME DEFAULT NULL COMMENT '创建时间',
  `CREATOR` VARCHAR(100) DEFAULT NULL COMMENT '创建人',
  PRIMARY KEY (`ID`),
  KEY `IDX_INCIDENT_NO` (`INCIDENT_NO`),
  KEY `IDX_SHEET_ID` (`SHEET_ID`),
  KEY `IDX_OCCUR_TIME` (`OCCUR_TIME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='公共事件表';

-- ============================================
-- 创建完成！
-- ============================================
-- 接下来导入数据：
-- mysql -u用户名 -p task_scheduler_dev < /Users/linziwang/Downloads/MW_ORDER_WORK_data.sql
-- mysql -u用户名 -p task_scheduler_dev < /Users/linziwang/Downloads/MW_ORDER_WORK_RELATED_data.sql
-- mysql -u用户名 -p task_scheduler_dev < /Users/linziwang/Downloads/MW_ORDER_CIRCULATE_data.sql
-- mysql -u用户名 -p task_scheduler_dev < /Users/linziwang/Downloads/MW_ORDER_CIRCULATE_INFO_data.sql
-- mysql -u用户名 -p task_scheduler_dev < /Users/linziwang/Downloads/MW_ORDER_PUBLIC_INCIDENT_data.sql
-- ============================================
