-- ============================================
-- MW_ORDER_WORK_RELATED 表结构 (MySQL)
-- ============================================

DROP TABLE IF EXISTS `MW_ORDER_WORK_RELATED`;

CREATE TABLE `MW_ORDER_WORK_RELATED` (
  `ID` VARCHAR(100) NOT NULL COMMENT '主键ID',
  `SHEET_ID` VARCHAR(100) DEFAULT NULL COMMENT '工单流水号',
  `RELATED_SHEET_ID` VARCHAR(100) DEFAULT NULL COMMENT '关联工单流水号',
  `RELATION_TYPE` VARCHAR(50) DEFAULT NULL COMMENT '关联类型',
  `REMARK` VARCHAR(500) DEFAULT NULL COMMENT '备注',
  `CREATE_TIME` DATETIME DEFAULT NULL COMMENT '创建时间',
  `UPDATE_TIME` DATETIME DEFAULT NULL COMMENT '更新时间',
  `CREATOR` VARCHAR(100) DEFAULT NULL COMMENT '创建人',
  `UPDATER` VARCHAR(100) DEFAULT NULL COMMENT '更新人',
  PRIMARY KEY (`ID`),
  KEY `IDX_SHEET_ID` (`SHEET_ID`),
  KEY `IDX_RELATED_SHEET_ID` (`RELATED_SHEET_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='工单关联关系表';
